# Generated by Django 3.1.7 on 2021-06-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210603_0008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriesmodel',
            options={'verbose_name': 'Kategoriler', 'verbose_name_plural': 'Kategoriler'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Ürünler', 'verbose_name_plural': 'Ürünler'},
        ),
        migrations.AlterModelOptions(
            name='productimages',
            options={'verbose_name': 'Ürün Resimleri', 'verbose_name_plural': 'Ürün Resimleri'},
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='', max_length=200),
        ),
    ]
