# Generated by Django 3.1.7 on 2021-06-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_remove_carousel_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyInfos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_account', models.CharField(blank=True, max_length=200, null=True, verbose_name='Instagram Adresi')),
                ('twitter_account', models.CharField(blank=True, max_length=200, null=True, verbose_name='Twitter Adresi')),
                ('facebook_account', models.CharField(blank=True, max_length=200, null=True, verbose_name='Facebook Adresi')),
                ('linkedin_account', models.CharField(blank=True, max_length=200, null=True, verbose_name='Linkedin Adresi')),
                ('phone_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='Telefon Numarası')),
                ('mail_adress', models.CharField(blank=True, max_length=200, null=True, verbose_name='Mail Adresi')),
            ],
        ),
    ]
