# Generated by Django 3.1.7 on 2021-06-02 21:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_myinfos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carousel',
            options={'verbose_name': 'Ayrı Resimler'},
        ),
        migrations.AlterModelOptions(
            name='contactmodel',
            options={'verbose_name': 'İletişim'},
        ),
        migrations.AlterModelOptions(
            name='myinfos',
            options={'verbose_name': 'Bilgilerim'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Sayfalar'},
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
