# Generated by Django 3.1.7 on 2021-06-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_auto_20210603_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='carousel',
            options={'verbose_name': 'Ayrı Resimler', 'verbose_name_plural': 'Resimler'},
        ),
        migrations.AlterModelOptions(
            name='contactmodel',
            options={'verbose_name': 'İletişim', 'verbose_name_plural': 'İletişimler'},
        ),
        migrations.AlterModelOptions(
            name='myinfos',
            options={'verbose_name': 'Bilgilerim', 'verbose_name_plural': 'Bilgiler'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Sayfalar', 'verbose_name_plural': 'Sayfalar'},
        ),
    ]
