# Generated by Django 3.1.7 on 2021-06-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_auto_20210604_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatjob',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='whyus',
            name='content',
            field=models.TextField(),
        ),
    ]
