# Generated by Django 3.1.7 on 2021-06-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0009_auto_20210604_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhoUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Biz Kimiz Bilgileri',
                'verbose_name_plural': 'Biz Kimiz',
            },
        ),
    ]
