# Generated by Django 3.1.7 on 2021-06-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0010_whous'),
    ]

    operations = [
        migrations.AddField(
            model_name='whous',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
