# Generated by Django 3.1.7 on 2021-06-04 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0011_whous_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corporate_mail_adress', models.CharField(blank=True, max_length=200, null=True)),
                ('corporate_phone_number', models.CharField(blank=True, max_length=200, null=True)),
                ('firma_kisa_adres', models.CharField(blank=True, max_length=450, null=True)),
                ('firma_harita_kodu', models.TextField(blank=True, null=True)),
                ('site_desc', models.TextField(blank=True, null=True)),
                ('site_keywords', models.TextField(blank=True, null=True)),
                ('smtp_mail_server', models.CharField(blank=True, max_length=200, null=True)),
                ('smtp_mail_name', models.CharField(blank=True, max_length=200, null=True)),
                ('smtp_mail_password', models.CharField(blank=True, max_length=200, null=True)),
                ('google_analytics', models.TextField(blank=True, null=True)),
                ('google_adsense', models.TextField(blank=True, null=True)),
                ('instagram_account', models.CharField(blank=True, max_length=200, null=True, verbose_name='Instagram Adresi')),
                ('twitter_account', models.CharField(blank=True, max_length=200, null=True, verbose_name='Twitter Adresi')),
                ('facebook_account', models.CharField(blank=True, max_length=200, null=True, verbose_name='Facebook Adresi')),
                ('linkedin_account', models.CharField(blank=True, max_length=200, null=True, verbose_name='Linkedin Adresi')),
                ('personal_phone_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='Telefon Numarası')),
                ('mail_adress', models.CharField(blank=True, max_length=200, null=True, verbose_name='Mail Adresi')),
            ],
            options={
                'verbose_name': 'Site Ayarları',
                'verbose_name_plural': 'Ayarlar',
            },
        ),
        migrations.DeleteModel(
            name='MyInfos',
        ),
    ]
