# Generated by Django 3.1.7 on 2021-06-04 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0013_auto_20210605_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='site_ismi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
