# Generated by Django 3.1.7 on 2021-06-04 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0014_sitesettings_site_ismi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='smtp_mail_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='smtp_mail_password',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='smtp_mail_server',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=''),
        ),
    ]
