# Generated by Django 3.1.7 on 2021-06-04 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0016_auto_20210605_0232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='smtp_host',
            new_name='smtp_port',
        ),
    ]
