# Generated by Django 3.1.7 on 2021-06-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0017_auto_20210605_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='firma_harita_kodu',
            field=models.TextField(blank=True, null=True, verbose_name='Harita Kodu(Google Maps Kodu)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='firma_kisa_adres',
            field=models.CharField(blank=True, max_length=450, null=True, verbose_name='Firma Kısa Adresi'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='firma_mail_adres',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Firmanın Mail Adresi'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='firma_telefonu',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Firma Telefon Numarası'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='google_adsense',
            field=models.TextField(blank=True, null=True, verbose_name='Google Adsense Kodu(Burayı Gerekmedikçe Değiştirmeyin)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='google_analytics',
            field=models.TextField(blank=True, null=True, verbose_name='Google Anaylytics Kodu(Burayı Gerekmedikçe Değiştirmeyin)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_aciklama',
            field=models.TextField(blank=True, null=True, verbose_name='Site Açıklaması(Site)(Google Kısmı)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_ismi',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Site İsmi(Nart Plastik olmalı)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_keywords',
            field=models.TextField(blank=True, null=True, verbose_name='Site Anahtar Kelimeleri(Keywords)'),
        ),
    ]
