# Generated by Django 3.1.7 on 2021-06-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0019_sitesettings_firma_harita_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='google_search',
            field=models.TextField(blank=True, null=True, verbose_name='Google Search Kodu(Burayı Gerekmedikçe Değiştirmeyin)'),
        ),
    ]
